trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Checkout the Azure DevOps repository
  - checkout: self
    persistCredentials: true

  # Install Terraform
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.5.0'

  # Set up AWS credentials from the service connection
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "Setting up AWS credentials"
        export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id --profile AwsConnect7)
        export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key --profile AwsConnect7)
        export AWS_DEFAULT_REGION='us-east-1' # Replace with your AWS region
    displayName: 'Set up AWS credentials'

  # Clone the GitHub repository
  - script: |
      git clone https://github.com/AnandJoy7/Terraform-Azure-DevOps-.git
    displayName: 'Clone GitHub Repository'

  # Run Terraform commands
  - script: |
      cd Terraform-Azure-DevOps-

      terraform init
      terraform plan
      terraform apply -auto-approve
    displayName: 'Terraform Init, Plan, and Apply'
