trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Checkout the Azure DevOps repository
  - checkout: self
    persistCredentials: true

  # Install Terraform
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.5.0'

  # Use AWS CLI Task to set up credentials
  - task: AWSCLI@1
    inputs:
      awsCredentials: 'AwsConnect7'   # Replace with your AWS service connection name
      regionName: 'us-east-1'         # Replace with your AWS region
      awsCommand: 's3'
      arguments: 'ls'
    displayName: 'Authenticate with AWS'

  # Clone the GitHub repository
  - script: |
      git clone https://github.com/AnandJoy7/Terraform-Azure-DevOps-.git
    displayName: 'Clone GitHub Repository'

  # Run Terraform commands
  - script: |
      cd Terraform-Azure-DevOps-/terraform-infra-deployment/terraform-s3

      # Export AWS credentials
      export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
      export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
      export AWS_DEFAULT_REGION='us-east-1' # Replace with your AWS region

      # Run Terraform commands
      terraform init
      terraform plan
      terraform apply -auto-approve
    displayName: 'Terraform Init, Plan, and Apply'
