trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: 'us-east-1'  # Replace with your desired AWS region

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install --user awscli
  displayName: 'Install AWS CLI'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWSConnection7'  # Use your service connection name
    awsRegion: 'us-east-1'            # Replace with your AWS region
    command: 's3'
    arguments: 'ls'
  displayName: 'Verify AWS Credentials'

- script: |
    curl -sLO https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_amd64.zip
    unzip terraform_1.3.6_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
  displayName: 'Install Terraform'

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform plan
  displayName: 'Terraform Plan'

- script: terraform apply -auto-approve
  displayName: 'Terraform Apply'

- task: Email@1
  inputs:
    to: 'your-email@example.com'  # Replace with your email address
    subject: 'Azure DevOps Pipeline Failed'
    body: 'The pipeline failed. Please check the logs.'
    condition: failed()
